### ISSUE TITLE
Issues with Coolline width modding

### ISSUE THREAD

**Issue by abdes** [SanUI/SanUI#13]
In
https://github.com/SanUI/SanUI/blob/48dc49fc013b9e67ab0ac9c79a5e1e8eb28a3b6c/SanUI/Modules/AddonMods/coolline.lua#L52-L53

The width setting is overridden by the setting in lines:

https://github.com/SanUI/SanUI/blob/48dc49fc013b9e67ab0ac9c79a5e1e8eb28a3b6c/SanUI/Modules/AddonMods/coolline.lua#L24-L25

Moreover, if the cool-downs contain a CD of more than 6 minutes, the button for that CD will appear outside of the Coolline and half of it will be on top of the leftmost button of bar 3.

Suggest to reduce Coolline width by at least half the size of button.

_PS: Examples of long CD_

> _https://www.wowhead.com/spell=388213/overload-elemental-deposit_
> _https://www.wowhead.com/spell=390392/overload-elemental-herb_
>

**Comment by SanUI** [comment]
Thanks for the report, shoudl be fixed in https://github.com/SanUI/SanUI/commit/42fc89ac36d19f2617972fbec1357e7ca9dcbcf1, please have a try and let me know :)

I realize that code overwriting thingy, but for some reason it was necessary to do it this way. I'm not sure why (something about first usage when coolline's db is not initialized maybe), but since it works, I don't want to touch that code :D
